name: DartBackend
description: A sample "Hello, World!" Functions Framework project.
# version: 0.1.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  functions_framework: ^0.4.0
  shelf: ^1.0.0
  shelf_router: ^1.1.1
  crypto: ^3.0.1
  mongo_dart: ^0.7.1
  dart_jsonwebtoken: ^2.3.2
  envify: ^2.0.2
  redis: ^2.0.0
  uuid: ^3.0.4

dev_dependencies:
  build_runner: ^2.0.0
  functions_framework_builder: ^0.4.0
  http: ^0.13.0
  test: ^1.15.7
  test_process: ^2.0.0
  shelf_router_generator: ^1.0.1
  envify_generator: ^2.0.2
